/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Callan' at '9/10/16 5:36 AM' with Gradle 2.6
 *
 * @author Callan, @date 9/10/16 5:36 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
