import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Callan' at '9/10/16 5:36 AM' with Gradle 2.6
 *
 * @author Callan, @date 9/10/16 5:36 AM
 */
public class LibraryTest {
    @Test
	public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
